# Generated by Django 5.1.6 on 2025-12-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
    ]
