# Generated by Django 5.1.6 on 2025-12-12 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_fooditem_carbs_fooditem_fat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_weight', models.FloatField(help_text='Weight in kg')),
                ('height', models.IntegerField(help_text='Height in cm')),
                ('goal', models.CharField(choices=[('SHRED', 'Shred (Fat Loss)'), ('BULK', 'Bulk (Muscle Gain)'), ('MAINTAIN', 'Maintain')], default='MAINTAIN', max_length=10)),
                ('activity_level', models.CharField(choices=[('SEDENTARY', 'Sedentary (Office Job)'), ('ACTIVE', 'Active (Daily Exercise)'), ('ATHLETE', 'Athlete (Physical Job/Sport)')], default='SEDENTARY', max_length=10)),
                ('daily_calorie_target', models.IntegerField(default=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
